# Search hidden files and directories
hidden = true

# Ignore files/directories matching pattern
ignore = [ ".git", "tmp", "node_modules", "bin", ".gitattributes", "composer.lock", ".sql" ]

color = true

smart-case = true
